### PR TITLE
Product listing page

### PR DESCRIPTION
**Pull request by nikhiljugale007**
Product listing page for e-commerce site.
Please review my PR

PRVIEW: https://deploy-preview-10--vercel-cart.netlify.app/product-page.html

### CODE REVIEW

**Review by Naman-Saxena1 — CHANGES_REQUESTED** [review]
Everything including component alignments and code looks fine 👍

**Review by prankurpandeyy — APPROVED** [review]

**Comment by prankurpandeyy** [comment]
use overflow as I can scroll to see the items below one cart to another , rest is looking good

**Review by Sahil25061999 — APPROVED** [review]
looks good nothing to suggest just add hover effect to clear button

**Comment by nikhiljugale007** [comment]
> use overflow as I can scroll to see the items below one cart to another , rest is looking good

Implemented suggestions.

**Pull request merged**
